spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${dbDefaultUrl}
    username: ${dbDefaultUsername}
    password: ${dbDefaultPw}
    driver-class-name: ${dbDefaultDriver}
  batch:
    job:
      enabled: false

  redis:
    host: localhost
    port: 6379


server:
  port: 8080

datasource:
  read:
    driver-class-name: ${dbDefaultDriver}
    url: ${dbDefaultUrl}
    user-name: ${dbDefaultUsername}
    password: ${dbDefaultPw}
  write:
    driver-class-name: ${dbDefaultDriver}
    url: ${dbDefaultUrl}
    user-name: ${dbDefaultUsername}
    password: ${dbDefaultPw}


logging.level.org.springframework.batch: DEBUG
ncloud:
  clientKey: ${ncloudClientKey}
  secretKey: ${ncloudSecretKey}

jwt:
  secretKey: dafdsvdavads
  accessExpiredAt: 86400
  refreshExpiredAt: 604800
cloud:
  aws:
    credentials:
      access-key: ${S3_IAM_ACCESS_KEY}
      secret-key: ${S3_IAM_SECRET_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    s3:
      bucketName: ${S3_BUCKET_NAME}


auth:
  permit:
    email: ["jinwoo794533@gmail.com", "chlaltnr7624@naver.com"]
springdoc:
  swagger-ui:
    path: /dsql-api-docs
    operations-sorter: method
    tags-sorter: method



